### ISSUE TITLE
Integrate in laravel project

### ISSUE THREAD

**Issue by sparrow84001** [MyScript/iinkTS#5]
Hello,

       I want to integrate iinkts to my laravel project. But not running simple Text recognition. Show only editor and nothing works. 
       Can you help me?

**Comment by leJsboureau** [comment]
Hello,
can you share us more details ?
maybe share your code or what don't work ? Have you an error message ?

**Comment by sparrow84001** [comment]
Hello, Thank you for your reply.
When I use div (div id="editor" touch-action="none">/div)  all functions work but the writing area is not showing and I can't write.
Then I used this canvas  (canvas id="editor" touch-action="none" style="border: 2px solid black;"></canvas) this time all functions were working but only the writing ink was not showing.
![Screenshot 2024-07-24 104217](https://github.com/user-attachments/assets/80e66593-7526-42d8-9061-3ea7f55cbebc)
This div uses pic.

**Comment by leJsboureau** [comment]
Hello,
According to the images, the canvas is not visible. may be because the svg layers (data-layer="CAPTURE" and data-layer="MODEL") are positioned absolutely with 100% height.  container (in our examples `<div id="editor">`) must therefore be of a defined height.

If that's not the cause, maybe you could share your code with us?

**Comment by sparrow84001** [comment]
Ok, I will share my code. Note that this is the PHP blade page.

[gg.docx](https://github.com/user-attachments/files/16358725/gg.docx)

**Comment by leJsboureau** [comment]
ok, it's definitely a problem with the height of the container. putting "height:100%" on the #editor div does not give a height and a relative height does not work if its parent does not have a height defined.
You must either:
- define a "concrete" height on the editor, for example: "height: calc(50dvh - 150px)"
- set a height on the parents so that the relative height of the div editor since applies

**Comment by sparrow84001** [comment]
Ok, thanks It works. I used "calc(100vh - 166px);"
Thanks for helping.

**Comment by leJsboureau** [comment]
You're welcome
